# Generated by Django 4.0.6 on 2022-07-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_alter_expert_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='expert',
        ),
    ]
